language: python

python:
  - "2.7"

install:
  # Clone the model dependencies
  - git clone https://github.com/weso/landportal_model model
  - cd model
  - git checkout staged-changes
  - cd ..
  # Install the rest of dependencies
  - "pip install --allow-all-external -r requirements.txt"

script:
  - "python tests.py"